// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSAX-XfFMnU4ld1oiD_4OE9XAs-s1Ct3w',
    appId: '1:13260836604:web:2597c0be73111ab2ba1179',
    messagingSenderId: '13260836604',
    projectId: 'examenavion',
    authDomain: 'examenavion.firebaseapp.com',
    storageBucket: 'examenavion.appspot.com',
    measurementId: 'G-1V9TD7VC2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyZRvgBTEvgKo7loIEZf4uQaWNEV4dsBI',
    appId: '1:13260836604:android:c2a5502f492db0afba1179',
    messagingSenderId: '13260836604',
    projectId: 'examenavion',
    storageBucket: 'examenavion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiCqqPn1Dty8gkuS9WPKg4C1PByD5JmdM',
    appId: '1:13260836604:ios:fabdd787c750ac70ba1179',
    messagingSenderId: '13260836604',
    projectId: 'examenavion',
    storageBucket: 'examenavion.appspot.com',
    iosBundleId: 'com.example.examenAvion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiCqqPn1Dty8gkuS9WPKg4C1PByD5JmdM',
    appId: '1:13260836604:ios:fabdd787c750ac70ba1179',
    messagingSenderId: '13260836604',
    projectId: 'examenavion',
    storageBucket: 'examenavion.appspot.com',
    iosBundleId: 'com.example.examenAvion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSAX-XfFMnU4ld1oiD_4OE9XAs-s1Ct3w',
    appId: '1:13260836604:web:f84c3c54c5a804ceba1179',
    messagingSenderId: '13260836604',
    projectId: 'examenavion',
    authDomain: 'examenavion.firebaseapp.com',
    storageBucket: 'examenavion.appspot.com',
    measurementId: 'G-GFJTS26SR5',
  );
}
